DATA:
  run_name: ddpm_land
  dataset_path: /content/Diffusion-Models-pytorch-module-compile/datasets/Landscape_classifier_02/training
  num_classes: 6
  image_size: 64

MODEL:
  unet: UNet_conditional
  ema: EMA

TRAIN:
  batch_size: 8
  device: cuda
  epochs: 300
  lr: 0.0003
  multigpu: false
  scheulder: false
  seed: 111
